os: windows
language: shell

install:
- choco install jdk11 -params "source=false"
- choco install maven

script:
- mvn package

notifications:
  email: false

deploy:
  - provider: releases
    api_key:
      secure: fYIKgl8EvLBYTG8ovd5P9LZVZIR/m3MnYMIPYQtoxYfiPeCTDzJxtGj+gRf5VbX9BgImvr3pWArOT09SCndjBlB63df4szGeuGXPTZMZzKPeaxZhyGo/OTMI2WiMoicrrkt3O024oWr719HL1Hd8Wa9FrV8isRS+bCy2WrTLa8PsclBsPy2onahrK8aAU3hvO0IogPpQz2mxgQ/KuZHdf0N7Xv0E2Qf9zyBFOZoJ5XSff8d3dJMofng7NoUsc8pFdCJmFuA+VlP61677R2OCNu2S4anoOX8g6PNHPD9SR/Itm8uQM7/Vcp4xo9Hn22h6D+kXVcJ0PaeKGctIC7JTNYrOziSORvyC8vHeUDt0u0s2WdOfju+76WN640Tz2EMLsuyIWDG7kyvTYdSUCp6ibQQLBXcZIpuVPfyd8dKjAkoItiuBKCIoN78CZfxRUs6fDFmxT73W6vCHOK+nsUVQseL2cCnn1MR9nGjTdQzXkRqCg/X6A1G8Qnmts9M1rg6kCTDoUo9dTAY2kDJ1wcXWjD28BKpxX16ya5NnMifkt6CGrS9zr+6VI0MgLdpsAj7W8AoVcCvquuaby0vpI/nGWo72hvrz/DDkp6m6MAWP2p+zNUaydouKSiGchs/QAEBrxGR53mWTZM2RqCxo+ycFQ7ofNZyy16IEc+e1twQol4o=
    file_glob: true
    file:
      - $TRAVIS_BUILD_DIR/target/SaveOrganizer.exe
    skip_cleanup: true
    on:
      tags: true
      branch: master