# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Pull Request build and merge

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Configure git
      run: "git config --global core.autocrlf false"
      shell: bash
    - uses: actions/checkout@v2 
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      shell: bash
      run: mvn -B package --file pom.xml
  merge:
    needs: build
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
    - name: Merge me!
      uses: ridedott/merge-me-action@v1.2.62
      with:
        GITHUB_TOKEN: ${{ secrets.MEH }}
        GITHUB_LOGIN: mckunda
        MERGE_METHOD: MERGE

