# This is a basic workflow to help you get started with Actions

name: Add tag

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Get XML Info
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        # The xml file from which to retrieve information.
        xml-file: pom.xml
        # The XPath of a node, to fetch its contents as output.
        xpath: /project/version

    # Runs a set of commands using the runners shell
    - name: Commit tagger
      uses: tvdias/github-tagger@v0.0.2
      with:
        # The GITHUB_TOKEN secret
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Tag text
        tag: v'/project/version'
